### ISSUE TITLE
Error Provisioning new cluster - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by uday31in** [Azure/AKS#1110]
```
{ "id": "/subscriptions/0dc96e8d-2fd9-41dc-863e-64ea5068192e/resourceGroups/m2-ne-prod-hub1-spoke1-aks/providers/Microsoft.Resources/deployments/template/operations/2BC590244C8FE312", "operationId": "2BC590244C8FE312", "properties": { "provisioningOperation": "Create", "provisioningState": "Running", "timestamp": "2019-07-16T12:33:41.2423856Z", "duration": "PT8M36.3539478S", "trackingId": "0f348310-41e3-44fe-aaf1-a8e341a34011", "statusCode": "InternalServerError", "statusMessage": { "code": "InternalOperationError", "message": "err: 'runtime error: invalid memory address or nil pointer dereference' stacktrace: 'goroutine 140465 [running]:\nruntime/debug.Stack(0xc001a0cca8, 0x55a06a830b20, 0x55a06bf39500)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngoms.io/aks/rp/pkg/microsoft.com/containerservice/filter.ErrorHandling.func1(0xc00003cfc0)\n\t/go/src/goms.io/aks/rp/pkg/microsoft.com/containerservice/filter/errorhandling.go:29 +0x59\npanic(0x55a06a830b20, 0x55a06bf39500)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b9\ngoms.io/aks/rp/vendor/github.com/Masterminds/semver.(*Version).Prerelease(...)\n\t/go/src/goms.io/aks/rp/vendor/github.com/Masterminds/semver/version.go:146\ngoms.io/aks/rp/vendor/github.com/Masterminds/semver.constraintGreaterThanEqual(0x0, 0xc001b40880, 0xc000e3b0b0)\n\t/go/src/goms.io/aks/rp/vendor/github.com/Masterminds/semver/constraints.go:283 +0x47\ngoms.io/aks/rp/vendor/github.com/Masterminds/semver.(*constraint).check(...)\n\t/go/src/goms.io/aks/rp/vendor/github.com/Masterminds/semver/constraints.go:159\ngoms.io/aks/rp/vendor/github.com/Masterminds/semver.Constraints.Check(0xc000952da0, 0x1, 0x1, 0x0, 0x0)\n\t/go/src/goms.io/aks/rp/vendor/github.com/Masterminds/semver/constraints.go:49 +0x85\ngoms.io/aks/rp/pkg/microsoft.com/containerservice/server/validation.(*ManagedClusterValidator).checkAzurePolicyOrchestratorVersion(0xc0010d44d0, 0xc000d6a6c0, 0x0)\n\t/go/src/goms.io/aks/rp/pkg/microsoft.com/containerservice/server/validation/managed_cluster_validator.go:967 +0xfa\ngoms.io/aks/rp/pkg/microsoft.com/containerservice/server/validation.(*ManagedClusterValidator).checkFeatureFlags(0xc0010d44d0, 0xc000bb2c90, 0x31)\n\t/go/src/goms.io/aks/rp/pkg/microsoft.com/containerservice/server/validation/managed_cluster_validator.go:889 +0xc9\ngoms.io/aks/rp/pkg/microsoft.com/containerservice/server/validation.(*ManagedClusterValidator).PrepareAndValidateManagedCluster(0xc0010d44d0, 0x55a06ab3b4c0, 0xc001217770, 0xc000bb2c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/goms.io/aks/rp/pkg/microsoft.com/containerservice/server/validation/managed_cluster_validator.go:92 +0x120\ngoms.io/aks/rp/pkg/microsoft.com/containerservice/server/operations/managedcluster.(*PutManagedClusterOperation).ValidateAndSaveGoalState(0xc0001a2310)\n\t/go/src/goms.io/aks/rp/pkg/microsoft.com/containerservice/server/operations/managedcluster/putmanagedcluster.go:194 +0x1486\ngoms.io/aks/rp/pkg/microsoft.com/containerservice/server/handlers.(*BaseHandler).ValidateAndPersistOperation(0xc00113bae0, 0xc000352a80, 0x55a06ab3b940, 0xc0001a2310)\n\t/go/src/goms.io/aks/rp/pkg/microsoft.com/containerservice/server/handlers/basehandler.go:32 +0x57\ngoms.io/aks/rp/pkg/microsoft.com/containerservice/server/handlers.(*ManagedClusterManager).PutManagedClusterHandler(0xc00113bae0, 0xc0012173b0, 0xc00003cfc0)\n\t/go/src/goms.io/aks/rp/pkg/microsoft.com/containerservice/server/handlers/managedclustermanager.go:176 +0x2be\ngoms.io/aks/rp/vendor/github.com/emicklei/go-restful.(*Container).dispatch.func6(0xc0012173b0, 0xc00003cfc0)\n\t/go/src/goms.io/aks/rp/vendor/github.com/emicklei/go-restful/container.go:267 +0x40\ngoms.io/aks/rp/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc001217440, 0xc0012173b0, 0xc00003cfc0)\n\t/go/src/goms.io/aks/rp/vendor/github.com/emicklei/go-restful/filter.go:21 +0x86\ngoms.io/aks/rp/pkg/microsoft.com/containerservice/filter.ErrorHandling(0xc0012173b0, 0xc00003cfc0, 0xc001217440)\n\t/go/src/goms.io/aks/rp/pkg/microsoft.com/containerservice/filter/errorhandling.go:40 +0x67\ngoms.io/aks/rp/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc001217440, 0xc0012173b0, 0xc00003cfc0)\n\t/go/src/goms.io/aks/rp/vendor/github.com/emicklei/go-restful/filter.go:19 +0x60\ngoms.io/aks/rp/pkg/microsoft.com/containerservice/filter.Context(0xc0012173b0, 0xc00003cfc0, 0xc001217440)\n\t/go/src/goms.io/aks/rp/pkg/microsoft.com/containerservice/filter/context.go:63 +0x624\ngoms.io/aks/rp/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc001217440, 0xc0012173b0, 0xc00003cfc0)\n\t/go/src/goms.io/aks/rp/vendor/github.com/emicklei/go-restful/filter.go:19 +0x60\ngoms.io/aks/rp/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc00108a090, 0x55a06ab38000, 0xc000a5a8c0, 0xc00129c000)\n\t/go/src/goms.io/aks/rp/vendor/github.com/emicklei/go-restful/container.go:269 +0x7df\nnet/http.HandlerFunc.ServeHTTP(0xc001146050, 0x55a06ab38000, 0xc000a5a8c0, 0xc00129c000)\n\t/usr/local/go/src/net/http/server.go:1995 +0x46\nnet/http.(*ServeMux).ServeHTTP(0xc00113d040, 0x55a06ab38000, 0xc000a5a8c0, 0xc00129c000)\n\t/usr/local/go/src/net/http/server.go:2375 +0x1d8\ngoms.io/aks/rp/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc00108a090, 0x55a06ab38000, 0xc000a5a8c0, 0xc00129c000)\n\t/go/src/goms.io/aks/rp/vendor/github.com/emicklei/go-restful/container.go:287 +0x4f\ngoms.io/aks/rp/pkg/core/httphandler.(*CustomHTTPHandler).ServeHTTP(0xc0011460c0, 0x55a06ab38000, 0xc000a5a8c0, 0xc00129c000)\n\t/go/src/goms.io/aks/rp/pkg/core/httphandler/customhttphandler.go:39 +0xa3\nnet/http.serverHandler.ServeHTTP(0xc000d881a0, 0x55a06ab38000, 0xc000a5a8c0, 0xc00129c000)\n\t/usr/local/go/src/net/http/server.go:2774 +0xaa\nnet/http.(*conn).serve(0xc001052000, 0x55a06ab3b400, 0xc001b40100)\n\t/usr/local/go/src/net/http/server.go:1878 +0x853\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2884 +0x2f6\n'" }, "targetResource": { "id": "/subscriptions/0dc96e8d-2fd9-41dc-863e-64ea5068192e/resourceGroups/m2-ne-prod-hub1-spoke1-aks/providers/Microsoft.ContainerService/ManagedClusters/m2-ne-prod-hub1-spoke1-aks1", "resourceType": "Microsoft.ContainerService/ManagedClusters", "resourceName": "m2-ne-prod-hub1-spoke1-aks1" } }}

```

**Comment by jnoller** [comment]
First, thank you for reaching out to the AKS team. 

AKS Github issues must be generally re-creatable (e.g here is the YAML/settings/packages/etc installed, can recreate the issue on existing clusters as well as newly created clusters). Unfortunately, this issue is cluster-specific.

For cluster specific issues (those that will require support and on-call staff to access you Subscription and clusters) we ask that you file an Azure Technical Support ticket with the identified issue, rec-creation steps if available, and link to this github thread.

**We can not ask** for the access, logs and other sensitive information on github, or ask you to email/slack/etc this information to us. Our portal ticketing system will protect the information including Subscription ids and credentials. If we discover as part of the root cause that this is an AKS or upstream bug, we will mark this issue as a known issue and ensure it is on the Product backlog as a repair item.

This will allow us to root-cause the issue and ensure it’s not specific to the environment or other configuration level issue - such as NSGs, custom network devices, etc.

Jesse
