### ISSUE TITLE
AKS windows dns issues

### ISSUE THREAD

**Issue by AmitDaniel-wsc** [Azure/AKS#1153]
**What happened**: Windows pods failed to resolve DNS

**What you expected to happen**: Pods should resolve DNS and access to remote endpoints

**How to reproduce it (as minimally and precisely as possible)**:

Create AKS windows cluster ( 1.14.5 version ) start any windows pod that should access public resource and you'll see the exception

For an example :

```
8/15/2019 08:59:42.3667075 Info: Overriding default configuration for environment Prod.
 8/15/2019 08:59:42.3810968 Info: Overwriting completed successfuly. Using settings for Prod
 8/15/2019 08:59:42.5126163 Info: App Init
 8/15/2019 08:59:42.5933483 Info: --------------
 Unhandled Exception: Microsoft.WindowsAzure.Storage.StorageException: The remote name could not be resolved: 'XXXXXX.queue.core.windows.net' ---> System.Net.WebException: The remote name could not be resolved: 'XXXXXX.queue.core.windows.net'
    at System.Net.HttpWebRequest.GetResponse()
    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 695
    --- End of inner exception stack trace ---
    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 604
    at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.Create(QueueRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 52
    at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.CreateIfNotExists(QueueRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 176
    at StorageUtils.Queues.GetQueue(String accountName, String queueName, Boolean autoCreate) in c:\agent\_work\5\s\ZoomInCloudSolution\Utils\StorageUtils\Queues\Queues.cs:line 87
    at StorageUtils.Queues.GetQueue(String accountName, String queueName) in c:\agent\_work\5\s\ZoomInCloudSolution\Utils\StorageUtils\Queues\Queues.cs:line 74
    at StorageUtils.WorkQueue..ctor(String QueueConfigName) in c:\agent\_work\5\s\ZoomInCloudSolution\Utils\StorageUtils\Queues\WorkQueue.cs:line 31
    at CliproUploadsCommon.ProcessQueue.MonitorQueue(ProcessorConfiguration config) in c:\agent\_work\5\s\ZoomInCloudSolution\WorkerRoles\CliproUploadsService\CliproUploadsCommon\ProcessQueue.cs:line 26
    at CliproUploadsConsole.Program.Main(String[] args) in c:\agent\_work\5\s\ZoomInCloudSolution\WorkerRoles\CliproUploadsService\CliproUploadsConsole\Program.cs:line 23
```

**Anything else we need to know?**:

```
Amits-MacBook-Pro:pr_validation amitdaniel$ kubectl get nodes
NAME                                STATUS   ROLES   AGE     VERSION
aks-nodepool1-21965609-vmss000002   Ready    agent   3m34s   v1.14.5
akswpool000000                      Ready    agent   22m     v1.14.5
```

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

```
- Size of cluster (how many worker nodes are in the cluster?) 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) 
- Others: Windows pods ( Dot net framework )

Thanks,
Amit

**Comment by dariuszbz** [comment]
Hello,

I have a lot windows pods and no problem like you .

Could you share your's yaml you use to create ?
Do you use deployment with load balancer to get connection to/from internet?


Cheers

**Comment by MikkelHegn** [comment]
Can you please check if the proposed solution here fixes this? https://github.com/Azure/AKS/issues/1029#issuecomment-519866646

**Comment by AmitDaniel-wsc** [comment]
Hi @dariuszbz 

This is the YAML i'm using.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uat-test-amit
  labels:
    environment: uat
    league: test
    service: amit
  namespace: wsc
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        service: cliprouploader
        environment: uat
        league: wsc
    spec:
      containers:
      - env:
        - name: RoleInstanceName
          value: uat-wsc-cliprouploader 
        - name: cliprouploaderVersion
          value: "cliprouploader.20190808.3" 
        - name: EnvName
          value: Uat
        name: cliprouploader
        image: XXX.azurecr.io/abc:abc.20190808.3
        imagePullPolicy: Always
      nodeSelector:
        beta.kubernetes.io/os: windows
      imagePullSecrets:
      - name: amitsecret
      dnsPolicy: Default
```

**Comment by AmitDaniel-wsc** [comment]
Hi @MikkelHegn I tried to remove the node pool and upgrade the cluster to 1.14.5 but seems that i'm facing the same issue.

**Comment by MikkelHegn** [comment]
What's the kernel version of the Windows nodes? Should be .557 if on the latest.

`kubectl describe nodes | grep -E "Name:|Kernel"`

**Comment by AmitDaniel-wsc** [comment]
Hi @MikkelHegn looks like i'm running with the latest version

Amits-MacBook-Pro:pr_validation amitdaniel$ kubectl describe nodes | grep -E "Name:|Kernel"


```
Name:               aks-nodepool1-21965609-vmss000002
 Kernel Version:             4.15.0-1052-azure
Name:               akswpool000000
 Kernel Version:             10.0.17763.557
```

**Comment by MikkelHegn** [comment]
Thx - there's still a scenario, where the networking stack can take a little while to set up in a Windows container. Can you try pausing before relying on the name resolution to complete?

E.g. for testing:
`kubectl run -it --rm --image=mcr.microsoft.com/windows/servercore:ltsc2019 --overrides='{"apiVersion":"v1","spec":{"Tolerations":[{"key":"windows", "operator":"Equal", "value":"true", "effect":"NoSchedule"}]}}' --generator=run-pod/v1 powershell.exe Resolve-DnsName www.microsoft.com`

versus

`kubectl run -it --rm --image=mcr.microsoft.com/windows/servercore:ltsc2019 --overrides='{"apiVersion":"v1","spec":{"Tolerations":[{"key":"windows", "operator":"Equal", "value":"true", "effect":"NoSchedule"}]}}' --generator=run-pod/v1 powershell.exe Start-Sleep 5; Resolve-DnsName www.microsoft.com`

!!Not verified, doesn't have a cluster handy... :-)

**Comment by MikkelHegn** [comment]
What's the base container image you're using?

**Comment by AmitDaniel-wsc** [comment]
Hi @MikkelHegn 

First of all here are the results of the command you asked me to run:

1.

```
Amits-MacBook-Pro:pr_validation amitdaniel$ kubectl run -it testing --rm --image=mcr.microsoft.com/windows/servercore:ltsc2019 --overrides='{"apiVersion":"v1","spec":{"Tolerations":[{"key":"windows", "operator":"Equal", "value":"true", "effect":"NoSchedule"}]}}' --generator=run-pod/v1 powershell.exe Resolve-DnsName www.microsoft.com
If you don't see a command prompt, try pressing enter.


Name                           Type   TTL   Section    NameHost
----                           ----   ---   -------    --------
www.microsoft.com              CNAME  20    Answer     www.microsoft.com-c-3.edgekey.net
www.microsoft.com-c-3.edgekey. CNAME  20    Answer     www.microsoft.com-c-3.edgekey.net.globalredir.akadns.net
net
www.microsoft.com-c-3.edgekey. CNAME  20    Answer     e13678.dspb.akamaiedge.net
net.globalredir.akadns.net

Name       : e13678.dspb.akamaiedge.net
QueryType  : AAAA
TTL        : 20
Section    : Answer
IP6Address : 2600:1406:3c:387::356e


Name       : e13678.dspb.akamaiedge.net
QueryType  : AAAA
TTL        : 20
Section    : Answer
IP6Address : 2600:1406:3c:385::356e


Name       : e13678.dspb.akamaiedge.net
QueryType  : A
TTL        : 5
Section    : Answer
IP4Address : 184.27.30.29
```

Second command :

```
Amits-MacBook-Pro:pr_validation amitdaniel$ kubectl run -it testing-sleep --rm --image=mcr.microsoft.com/windows/servercore:ltsc2019 --overrides='{"apiVersion":"v1","spec":{"Tolerations":[{"key":"windows", "operator":"Equal", "value":"true", "effect":"NoSchedule"}]}}' --generator=run-pod/v1 powershell.exe 'Start-Sleep 5; Resolve-DnsName www.microsoft.com'
If you don't see a command prompt, try pressing enter.


Name                           Type   TTL   Section    NameHost
----                           ----   ---   -------    --------
www.microsoft.com              CNAME  5     Answer     www.microsoft.com-c-3.edgekey.net
www.microsoft.com-c-3.edgekey. CNAME  5     Answer     www.microsoft.com-c-3.edgekey.net.globalredir.akadns.net
net
www.microsoft.com-c-3.edgekey. CNAME  5     Answer     e13678.dspb.akamaiedge.net
net.globalredir.akadns.net

Name       : e13678.dspb.akamaiedge.net
QueryType  : AAAA
TTL        : 5
Section    : Answer
IP6Address : 2600:1406:3c:387::356e


Name       : e13678.dspb.akamaiedge.net
QueryType  : AAAA
TTL        : 5
Section    : Answer
IP6Address : 2600:1406:3c:385::356e


Name       : e13678.dspb.akamaiedge.net
QueryType  : A
TTL        : 17
Section    : Answer
IP4Address : 184.26.130.117
```

Also the base image i'm using is : FROM mcr.microsoft.com/dotnet/framework/runtime:4.7.2-20190611-windowsservercore-ltsc2019


Thanks for all your help !

**Comment by MikkelHegn** [comment]
I think the dnsPolicy setting might be to blame here. If I set it to 'Deafult', my resolution also breaks.

The difference I see in the configuration in the container is the PrimaryDnsSuffix being empty when the dnsPolicy is not set, as opposed to being 'Node' when the dnsPolicy is set to 'Default'. Is there a particular reason you're overwriting that setting (Note: Default is not the default setting :-) - https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy).

@PatrickLang / @feiskyer / @craiglpeters : Can either of you help us understand this?

**Comment by AmitDaniel-wsc** [comment]
@MikkelHegn What should be the default dnsPolicy ? I can change it and check if everything is good .

**Comment by MikkelHegn** [comment]
There is no should, only options depending on what you require :-). The default behavior is to set it to 'ClusterFirst', or not set it - please read the link I pasted above.

**Comment by dariuszbz** [comment]
Windows core, windows nano, with and without sdk and/or .net or core .
As said I have a lot.

**Comment by AmitDaniel-wsc** [comment]
@MikkelHegn Hi again :-)
Thanks for your help - I changed the dnsPolicy to be : ClusterFirst and all the pods are working as expected !!
