### ISSUE TITLE
Unable to do AKS browse

### ISSUE THREAD

**Issue by ejstan** [Azure/AKS#1174]
**What Happenned:** Using aks browse on our existing Azure Kubernetes Service is not working anymore. It was working before since August 23, 2019. Now encountering the following issue everytime I'm doing aks browse. There were no changes at all on our configuration for the past 2 weeks.

`Proxy running on http://127.0.0.1:8001/
Press CTRL+C to close the tunnel...
Forwarding from 127.0.0.1:8001 -> 9090
Handling connection for 8001
E0829 15:11:44.080975   16724 portforward.go:331] an error occurred forwarding 8001 -> 9090: error forwarding port 9090 to pod 6cf77fbbb54ea69894664bfe11cfe57e7789f153ea6da576c685c6c69bd56c18, uid : exit status 1: 2019/08/29 07:12:42 socat[90059] E connect(6, AF=2 127.0.0.1:9090, 16): Connection refused
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-bb1gu7gd\azure-cli-acs\azure\cli\command_modules\acs\custom.py", line 94, in wait_then_open
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response`

**Comment by TomGeske** [comment]
@ejstan: Can you retry using latest CLI tooling?

**Comment by ejstan** [comment]
> @ejstan: Can you retry using latest CLI tooling?

Already resolved this months ago. Thanks
