### ISSUE TITLE
Windows Container without network connectivity right after start

### ISSUE THREAD

**Issue by dhilgarth** [Azure/AKS#1390]
We are currently investigating Windows containers on AKS and are coming across what seems to be a race condition.

We are creating Job resources. These jobs create a pod with a huge 15GB windows image (some containerized legacy software that needs a full windows).
The command of the container runs a .NET Core 3.0 commandline tool that tries to connect to an external API. This *sometimes* fails with `System.Net.Http.HttpRequestException: No such host is known`.

The issue is not a DNS issue, because using the IP address also has this problem.
It's also not a performance issue because this happens even when we create only a single job.

If we wait for ten seconds after the start of the application, it always succeeds.
It looks like the container is up and running our application before it has fully been connected to the network.

Is this a known issue?

**Environment**:
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster: 1 linux node, 3 windows nodes

**Comment by dhilgarth** [comment]
More info:

This is the code that we execute right after the start:

```private static async Task CheckConnectivity(ILogger<Program> logger)
        {
            logger.LogInformation("Checking general connectivity...");
            try
            {
                logger.LogInformation($"Network connectivity state: {NetworkInterface.GetIsNetworkAvailable()}");
                var options = new JsonSerializerOptions {WriteIndented = true};
                var nics = NetworkInterface.GetAllNetworkInterfaces();
                logger.LogInformation(JsonSerializer.Serialize(nics.Select(x => x.GetIPProperties().GetIPv4Properties())));
                logger.LogInformation(JsonSerializer
                    .Serialize(nics.Select(x => x.GetIPProperties().GatewayAddresses.Select(y => y.Address.ToString())))
                    );
                string localIP;
                using (Socket socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, 0))
                {
                    socket.Connect("8.8.8.8", 65530);
                    IPEndPoint endPoint = socket.LocalEndPoint as IPEndPoint;
                    localIP = endPoint.Address.ToString();
                    logger.LogInformation(localIP);
                }

                logger.LogInformation(JsonSerializer.Serialize(nics, options));

                using var httpClient = new HttpClient();
                logger.LogInformation("Using IP...");
                var result = await httpClient.GetStringAsync("http://172.217.22.78");
                logger.LogInformation($"Successfully got {result.Length} bytes from Google via IP");
                logger.LogInformation("Using DNS...");
                result = await httpClient.GetStringAsync("https://google.com");
                logger.LogInformation($"Successfully got {result.Length} bytes from Google via DNS");
            }
            catch (Exception e)
            {
                logger.LogError(e, "Connectivity check failed. Waiting ten seconds and trying again.");
                Thread.Sleep(TimeSpan.FromSeconds(10));
                CheckConnectivity(logger);
            }
        }```

And this is the output generated by it when we encounter the issue:

```info: AKSIssuesTester[0]
      Checking general connectivity...
info: AKSIssuesTester[0]
      Network connectivity state: True
info: AKSIssuesTester[0]
      [{"UsesWins":false,"IsDhcpEnabled":true,"IsAutomaticPrivateAddressingActive":false,"IsAutomaticPrivateAddressingEnabled":true,"Index":23,"IsForwardingEnabled":false,"Mtu":1500},{"UsesWins":false,"IsDhcpEnabled":false,"IsAutomaticPrivateAddressingActive":false,"IsAutomaticPrivateAddressingEnabled":true,"Index":22,"IsForwardingEnabled":false,"Mtu":-1}]
info: AKSIssuesTester[0]
      [["10.240.0.1"],[]]
info: AKSIssuesTester[0]
      10.240.0.41
info: AKSIssuesTester[0]
      [
        {
          "Id": "{B42DFA3E-BE2A-4C06-AE26-50E7D7258907}",
          "Name": "vEthernet (b60fb4ee-eth0)",
          "Description": "Hyper-V Virtual Ethernet Adapter #3",
          "OperationalStatus": 1,
          "Speed": 40000000000,
          "IsReceiveOnly": false,
          "SupportsMulticast": true,
          "NetworkInterfaceType": 6
        },
        {
          "Id": "{99E94640-382F-11EA-BB34-CC1B4490DA36}",
          "Name": "Loopback Pseudo-Interface 2",
          "Description": "Software Loopback Interface 2",
          "OperationalStatus": 1,
          "Speed": 1073741824,
          "IsReceiveOnly": false,
          "SupportsMulticast": true,
          "NetworkInterfaceType": 24
        }
      ]
info: AKSIssuesTester[0]
      Using IP...
fail: AKSIssuesTester[0]
      Connectivity check failed. Waiting ten seconds and trying again.
System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at AKSIssuesTester.CheckConnectivity(ILogger`1 logger) in C:\src\AKSIssuesTester\Program.cs:line 68
info: AKSIssuesTester[0]
      Checking general connectivity...
info: AKSIssuesTester[0]
      Network connectivity state: True
info: AKSIssuesTester[0]
      [{"UsesWins":false,"IsDhcpEnabled":false,"IsAutomaticPrivateAddressingActive":false,"IsAutomaticPrivateAddressingEnabled":true,"Index":23,"IsForwardingEnabled":false,"Mtu":1500},{"UsesWins":false,"IsDhcpEnabled":false,"IsAutomaticPrivateAddressingActive":false,"IsAutomaticPrivateAddressingEnabled":true,"Index":22,"IsForwardingEnabled":false,"Mtu":-1}]
info: AKSIssuesTester[0]
      [["10.240.0.1"],[]]
info: AKSIssuesTester[0]
      10.240.0.41
info: AKSIssuesTester[0]
      [
        {
          "Id": "{B42DFA3E-BE2A-4C06-AE26-50E7D7258907}",
          "Name": "vEthernet (b60fb4ee-eth0)",
          "Description": "Hyper-V Virtual Ethernet Adapter #3",
          "OperationalStatus": 1,
          "Speed": 40000000000,
          "IsReceiveOnly": false,
          "SupportsMulticast": true,
          "NetworkInterfaceType": 6
        },
        {
          "Id": "{99E94640-382F-11EA-BB34-CC1B4490DA36}",
          "Name": "Loopback Pseudo-Interface 2",
          "Description": "Software Loopback Interface 2",
          "OperationalStatus": 1,
          "Speed": 1073741824,
          "IsReceiveOnly": false,
          "SupportsMulticast": true,
          "NetworkInterfaceType": 24
        }
      ]
info: AKSIssuesTester[0]
      Using IP...
info: AKSIssuesTester[0]
      Successfully got 47147 bytes from Google via IP
info: AKSIssuesTester[0]
      Using DNS...
info: AKSIssuesTester[0]
      Successfully got 47157 bytes from Google via DNS```

The only difference I am noting is this: `IsDhcpEnabled` is `true` on the first attempt that fails and it then is `false` when the connectivity check succeeds.

**Comment by dhilgarth** [comment]
I have just verified that `IsDhcpEnabled` is `false` when the first connectivity test succeeds:

```
info: AKSIssuesTester[0]
      Tester started
info: AKSIssuesTester[0]
      Checking general connectivity...
info: AKSIssuesTester[0]
      Network connectivity state: True
info: AKSIssuesTester[0]
      [{"UsesWins":false,"IsDhcpEnabled":false,"IsAutomaticPrivateAddressingActive":false,"IsAutomaticPrivateAddressingEnabled":true,"Index":23,"IsForwardingEnabled":false,"Mtu":1500},{"UsesWins":false,"IsDhcpEnabled":false,"IsAutomaticPrivateAddressingActive":false,"IsAutomaticPrivateAddressingEnabled":true,"Index":22,"IsForwardingEnabled":false,"Mtu":-1}]
info: AKSIssuesTester[0]
      [["10.240.0.1"],[]]
info: AKSIssuesTester[0]
      10.240.0.101
info: AKSIssuesTester[0]
      [
        {
          "Id": "{7A3EC04E-A0D6-4788-A816-63793798BBF5}",
          "Name": "vEthernet (1a133c3f-eth0)",
          "Description": "Hyper-V Virtual Ethernet Adapter #3",
          "OperationalStatus": 1,
          "Speed": 40000000000,
          "IsReceiveOnly": false,
          "SupportsMulticast": true,
          "NetworkInterfaceType": 6
        },
        {
          "Id": "{981F9EA5-382F-11EA-BB34-CA05B4EC60C8}",
          "Name": "Loopback Pseudo-Interface 2",
          "Description": "Software Loopback Interface 2",
          "OperationalStatus": 1,
          "Speed": 1073741824,
          "IsReceiveOnly": false,
          "SupportsMulticast": true,
          "NetworkInterfaceType": 24
        }
      ]
info: AKSIssuesTester[0]
      Using IP...
info: AKSIssuesTester[0]
      Successfully got 47212 bytes from Google via IP
info: AKSIssuesTester[0]
      Using DNS...
info: AKSIssuesTester[0]
      Successfully got 47220 bytes from Google via DNS
```

**Comment by dhilgarth** [comment]
What I find very interesting is that the UDP connection to 8.8.8.8 succeeds in any case. Only the HTTP connection needs some time to be successful.

**Comment by zhiweiv** [comment]
I think it is same issue with https://github.com/Azure/azure-container-networking/issues/341.

**Comment by dhilgarth** [comment]
I agree @zhiweiv

**Comment by MikkelHegn** [comment]
Let's keep it open here as a tracking item and we will update, once the problem get fixed upstream and new bits released to AKS.
