### ISSUE TITLE
"ERROR: argument of type 'NoneType' is not iterable" received when enabling addons via Azure CLI

### ISSUE THREAD

**Issue by Shuanglu** [Azure/AKS#1432]
**What happened**:
failed to enable the addon of dashboard via CLI
**What you expected to happen**:
enable addon of dashboard
**How to reproduce it (as minimally and precisely as possible)**:
az aks enable-addons -a kube-dashboard -g xx -n xx

**Anything else we need to know?**:
I didn't enable the monitoring addon
debug output
WARNING: The behavior of this command has been altered by the following extension: aks-preview
ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/home/shuanglu1993/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1964, in aks_enable_addons
    _ensure_container_insights_for_monitoring(cmd, instance.addon_profiles['omsagent'])
  File "/home/shuanglu1993/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 1516, in _ensure_container_insights_for_monitoring
    **if 'loganalyticsworkspaceresourceid' in addon.config:
TypeError: argument of type 'NoneType' is not iterable**
WARNING:
To open an issue, please run: 'az feedback'
**Environment**:
{
  "azure-cli": "2.0.80",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.0.80",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aks-preview": "0.4.24",
    "log-analytics": "0.1.3"
  }
}
- Kubernetes version (use `kubectl version`): 1.16
- Size of cluster (how many worker nodes are in the cluster?) 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) N/A
- Others:
N/A

**Comment by jluk** [comment]
Thanks for the report here, we have this issue open on the azure-cli as well for reference. We are scheduling fixes for this.

https://github.com/Azure/azure-cli/issues/11456

**Comment by jluk** [comment]
@shuanglu I'm going to close this aks issue as a duplicate, please follow the related issue I shared above which now has an active PR to address it. Thanks!
