### ISSUE TITLE
az aks get-credentials doesn't work

### ISSUE THREAD

**Issue by przemolb** [Azure/AKS#158]
Hello,
I am trying to create k8s cluster using https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough but am facing the following problem:
```
az aks get-credentials --resource-group k8s --name my-k8s
'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 337, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1338, in aks_get_credentials
    _print_or_merge_credentials(path, kubeconfig)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 1478, in _print_or_merge_credentials
    merge_kubernetes_configurations(path, temp_path)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 930, in merge_kubernetes_configurations
    existing = yaml.safe_load(stream)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/yaml/__init__.py", line 70, in load
    loader = Loader(stream)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte
```
```
az --version
azure-cli (2.0.25)
...
on macOS High Sierra
```
Can anyone please hint me what is the problem with it ?

**Comment by mboersma** [comment]
@przemolb my guess is that your local ~/.kube/config file somehow didn't parse as valid YAML. After we fetch the remote credentials, we do a merge of your local config and the remote one, and that expects both sides to be valid YAML documents. (We need a better error message here--I'll fix that.)

Try this to be sure:
```
$ cp ~/.kube/config ~/.kube/config.bak
$ az aks get-credentials --resource-group k8s --name my-k8s
```

If that succeeds, then there was something in ~/.kube/config.bak that didn't parse as YAML, and you'd need to hand-merge the two configurations. Let me know what you find.

**Comment by przemolb** [comment]
@mboersma thanks, that helped. I used 'mv' instead of 'cp' of course :-)

**Comment by mboersma** [comment]
D’oh yes, I meant `mv`. 😊

In the next version of the `az` CLI, this will result in a more useful error message that will name the file and say why it failed to parse.

**Comment by bbad123** [comment]
It was very helpful for me.
Thank you.
