### ISSUE TITLE
Upgrade to 1.8.7 Failed

### ISSUE THREAD

**Issue by ElanHasson** [Azure/AKS#165]
When trying to upgrade I received the following error and the result is a failed deployment.

  "correlationId": "c64550d2-c447-4b46-8b2a-7b74732f45c5

` az aks upgrade --name platyformK8sCluster --resource-group Platyformk8s --kubernetes-version 1.8.7
Kubernetes may be unavailable during cluster upgrades.
Are you sure you want to perform this operation? (y/n): y
Exception in thread AzureOperationPoller(9321ee69-bbf3-49a6-b892-745bc5597f86):
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrestazure\azure_operation.py", line 377, in _start
    self._poll(update_cmd)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrestazure\azure_operation.py", line 464, in _poll
    raise OperationFailed("Operation failed or cancelled")
msrestazure.azure_operation.OperationFailed: Operation failed or cancelled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrestazure\azure_operation.py", line 388, in _start
    self._exception = CloudError(self._response)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrestazure\azure_exceptions.py", line 157, in __init__
    self._build_error_data(response)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrestazure\azure_exceptions.py", line 173, in _build_error_data
    self.error = self.deserializer('CloudErrorRoot', response).error
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\serialization.py", line 1021, in __call__
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\serialization.py", line 1185, in deserialize_data
    return self(obj_type, data)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\serialization.py", line 1028, in __call__
    return self._instantiate_model(response, d_attrs, additional_properties)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrest\serialization.py", line 1130, in _instantiate_model
    response_obj = response(**kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrestazure\azure_exceptions.py", line 62, in __init__
    self.message = kwargs.get('message')
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\msrestazure\azure_exceptions.py", line 114, in message
    value = eval(value)
  File "<string>", line 1, in <module>
NameError: name 'CloudProviderProfile' is not defined

{
  "additionalProperties": {
    "endTime": "2018-02-06T07:11:41.9322239Z",
    "error": {
      "code": "ControlPlaneCloudProviderNotSet",
      "message": "CloudProviderProfile is not set"
    },
    "startTime": "2018-02-06T07:10:29.3434923Z",
    "status": "Failed"
  },
  "agentPoolProfiles": null,
  "dnsPrefix": null,
  "fqdn": null,
  "id": null,
  "kubernetesVersion": null,
  "linuxProfile": null,
  "location": null,
  "name": "96f620a1-a47c-6844-a89f-6afb7529a42d",
  "provisioningState": null,
  "servicePrincipalProfile": null,
  "tags": null,
  "type": null
}`

**Comment by ElanHasson** [comment]
I've retried several times and I get the same result.

**Comment by audaxocles** [comment]
I'm having the same issue.  Have you found a resolution?

**Comment by ElanHasson** [comment]
Had to delete and recreate :(

I guess it's a test (a la chaos monkey) to ensure your data is kept off of the containers in persistent storage :)

**Comment by audaxocles** [comment]
Haha...  Yeah -- I'm currently stateless so I'm good there.  :)  Thanks!   I'll do that then.  Cheers.

**Comment by ElanHasson** [comment]
Thankfully so am I.

**Comment by slack** [comment]
The latest build has fixes for a few bugs around missing `CloudProviderProfile`. Should be rolling out this week.

Going to close this specific issue, re-open if it comes back!
