### ISSUE TITLE
Unable to reset SP secret to AKS cluster

### ISSUE THREAD

**Issue by bvenkatbm** [Azure/AKS#2353]
**What happened**:
My SP's client secret of AKS cluster expired. Following [Azure](https://docs.microsoft.com/en-us/azure/aks/update-credentials#reset-the-existing-service-principal-credential) documentation tried to reset SP credentials. AKS is throwing Internal Server Error. Its a blocker because we are unable to pull images from ACR.

Please find the debug logs/stack trace of Internal server error:
```
msrest.http_logger: {
  "name": "3826f132-e36b-e945-8f33-efea9b72b815",
  "status": "Failed",
  "startTime": "2021-05-25T13:48:00.7033333Z",
  "endTime": "2021-05-25T15:08:51.8956559Z",
  "error": {
   "code": "InternalOperationError",
   "message": "Internal server error"
  }
 }
msrest.exceptions: Internal server error
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrestazure/polling/arm_polling.py", line 390, in run
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrestazure/polling/arm_polling.py", line 418, in _poll
msrestazure.polling.arm_polling.OperationFailed: Operation failed or cancelled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 987, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/polling/poller.py", line 183, in result
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/polling/poller.py", line 201, in wait
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrest/polling/poller.py", line 152, in _start
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msrestazure/polling/arm_polling.py", line 400, in run
msrestazure.azure_exceptions.CloudError: Azure Error: InternalOperationError
Message: Internal server error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 702, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 997, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 131, in handle_long_running_operation_exception
knack.util.CLIError: Deployment failed. Correlation ID: 957bfbd6-9712-4ed7-a033-0e97041c8786. Internal server error

cli.azure.cli.core.azclierror: Deployment failed. Correlation ID: 957bfbd6-9712-4ed7-a033-0e97041c8786. Internal server error
az_command_data_logger: Deployment failed. Correlation ID: 957bfbd6-9712-4ed7-a033-0e97041c8786. Internal server error
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03FF0100>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 4862.873 seconds (init: 0.221, invoke: 4862.652)
```

**What you expected to happen**:
SP client secret should be updated to the new one on all nodes.

**How to reproduce it (as minimally and precisely as possible)**:
```
SP_ID=$(az aks show --resource-group myResourceGroup --name myAKSCluster \
    --query servicePrincipalProfile.clientId -o tsv)

SP_SECRET=$(az ad sp credential reset --name $SP_ID --query password -o tsv)

az aks update-credentials \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --reset-service-principal \
    --service-principal $SP_ID \
    --client-secret $SP_SECRET
```

**Environment**:
- Kubernetes version:  
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"ea670c3ed1fab723e191551e68da613f8a9c5667", GitTreeState:"clean", BuildDate:"2020-05-30T04:43:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster: 15 nodes with 1 node pool
- General description of workloads in the cluster:  HTTP microservices, Java app (Spring boot framework)
- Others:
    - AKS is not using Managed Identity.
    - new SP client secret generated satisfies this regex `[a-zA-Z0-9.]`.
    - Also in debugging I found out that some nodes have the updated. We ran this shell command(`cat /etc/kubernetes/azure.json`) in our VMSS to know the status.
    - Node config: Standard_D1_v2
    - Cluster uses availability sets

**Comment by bvenkatbm** [comment]
Updated AKS version to latest and everything works as normal.
