### ISSUE TITLE
Aks pod couldn't able to connect to azure SQL database 

### ISSUE THREAD

**Issue by balakrishna222111** [Azure/AKS#2464]
I have created a azure aks cluster with this command 
`az aks create 
    --resource-group $ResourceGroupName 
    --name $AksClusterName 
    --node-count 2 
    --network-plugin azure  
    --service-cidr 172.18.0.0/16 
    --dns-service-ip 172.18.0.0 
    --docker-bridge-address 172.17.0.1/16 
    --vnet-subnet-id $SUBNET_ID 
    --disable-rbac 
    --node-vm-size Standard_DS3_v2 
    --network-policy azure
`

AKS cluster also created successfully. Now i deployed one pod in aks cluster which will communicate with Azure SQL DB.

But pod is couldn't able to communicate with SQL DB . Even though i added AKS subnet IP and Node-ip in SQL DB fire-wall 

SQL DB Firewall:-
-------------------
![image](https://user-images.githubusercontent.com/22685723/127650922-15d0c3d4-4ad0-4dab-8756-290f523e072d.png)

AKS SUBNET :-
------------------------
![image](https://user-images.githubusercontent.com/22685723/127651041-735d6f9d-ce77-4a06-94f6-0b214e7acefa.png)

POD logs:-
--------------

  at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host test-sqlserver-server-prod-01.database.windows.net, port 1433 has failed. Error: "test-sqlserver-server-prod-01.database.windows.net: Temporary failure in name resolution. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234)
        at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:285)
        at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2434)
        at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:659)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2546)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2216)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2067)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1204)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:825)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:476)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:442)
        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
        ... 35 more

AKS Configuration:-
----------------------
![image](https://user-images.githubusercontent.com/22685723/127651310-b9d5eeed-7d96-4349-a838-5797fa150cc3.png)

**Comment by rishabhsaha** [comment]
Can you provide more details around the Azure SQL? Are there private links/private endpoints involved? Can you spin up a VM in the same VNET as the AKS cluster and connect /resolve to the SQL Server?
