### ISSUE TITLE
Crashloop of `csi-azuredisk-node` `DeamonSet` on `standard_nd12s` nodes

### ISSUE THREAD

**Issue by mboutet** [Azure/AKS#2530]
**What happened**:

Logs from `azuredisk` container in `csi-azuredisk-node` `DeamonSet`:
<details>
  <summary>Click to expand!</summary>
  
```
I0901 15:25:00.931486       1 main.go:89] set up prometheus server on [::]:29605
I0901 15:25:00.931680       1 azuredisk.go:168] 
DRIVER INFORMATION:
-------------------
Build Date: "2021-06-15T07:15:17Z"
Compiler: gc
Driver Name: disk.csi.azure.com
Driver Version: v1.4.0
Git Commit: e846f0b0b6f99d9868980ce0ef7e93adc7f3f1a2
Go Version: go1.16.4
Platform: linux/amd64
Topology Key: topology.disk.csi.azure.com/zone

Streaming logs below:
I0901 15:25:00.932883       1 azure.go:72] reading cloud config from secret
E0901 15:25:01.077986       1 azure_config.go:45] Failed to get cloud-config from secret: failed to get secret kube-system/azure-cloud-provider: secrets "azure-cloud-provider" not found
I0901 15:25:01.078007       1 azure.go:75] InitializeCloudFromSecret failed with error: InitializeCloudFromSecret: failed to get cloud config from secret kube-system/azure-cloud-provider: failed to get secret kube-system/azure-cloud-provider: secrets "azure-cloud-provider" not found
I0901 15:25:01.078011       1 azure.go:80] could not read cloud config from secret
I0901 15:25:01.078017       1 azure.go:83] AZURE_CREDENTIAL_FILE env var set as /etc/kubernetes/azure.json
I0901 15:25:01.078032       1 azure.go:102] read cloud config from file: /etc/kubernetes/azure.json successfully
I0901 15:25:01.078538       1 azure_auth.go:115] azure: using client_id+client_secret to retrieve access token
I0901 15:25:01.078571       1 azure.go:654] Azure cloudprovider using try backoff: retries=6, exponent=1.500000, duration=5, jitter=1.000000
I0901 15:25:01.078606       1 azure_interfaceclient.go:70] Azure InterfacesClient (read ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078612       1 azure_interfaceclient.go:73] Azure InterfacesClient (write ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078623       1 azure_vmsizeclient.go:68] Azure VirtualMachineSizesClient (read ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078626       1 azure_vmsizeclient.go:71] Azure VirtualMachineSizesClient (write ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078643       1 azure_snapshotclient.go:69] Azure SnapshotClient (read ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078648       1 azure_snapshotclient.go:72] Azure SnapshotClient (write ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078654       1 azure_storageaccountclient.go:69] Azure StorageAccountClient (read ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078657       1 azure_storageaccountclient.go:72] Azure StorageAccountClient (write ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078666       1 azure_diskclient.go:67] Azure DisksClient using API version: 2020-12-01
I0901 15:25:01.078676       1 azure_diskclient.go:72] Azure DisksClient (read ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078679       1 azure_diskclient.go:75] Azure DisksClient (write ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078686       1 azure_vmclient.go:69] Azure VirtualMachine client (read ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078689       1 azure_vmclient.go:72] Azure VirtualMachine client (write ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078695       1 azure_vmssclient.go:69] Azure VirtualMachineScaleSetClient (read ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078698       1 azure_vmssclient.go:72] Azure VirtualMachineScaleSetClient (write ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078704       1 azure_vmssvmclient.go:70] Azure vmssVM client (read ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078707       1 azure_vmssvmclient.go:73] Azure vmssVM client (write ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078716       1 azure_routeclient.go:67] Azure RoutesClient (read ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078720       1 azure_routeclient.go:70] Azure RoutesClient (write ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078725       1 azure_subnetclient.go:68] Azure SubnetsClient (read ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078736       1 azure_subnetclient.go:71] Azure SubnetsClient (write ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078742       1 azure_routetableclient.go:67] Azure RouteTablesClient (read ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078745       1 azure_routetableclient.go:70] Azure RouteTablesClient (write ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078751       1 azure_loadbalancerclient.go:69] Azure LoadBalancersClient (read ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078760       1 azure_loadbalancerclient.go:72] Azure LoadBalancersClient (write ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078765       1 azure_securitygroupclient.go:69] Azure SecurityGroupsClient (read ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078769       1 azure_securitygroupclient.go:72] Azure SecurityGroupsClient (write ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078775       1 azure_publicipclient.go:70] Azure PublicIPAddressesClient (read ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078782       1 azure_publicipclient.go:73] Azure PublicIPAddressesClient (write ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078790       1 azure_vmasclient.go:69] Azure AvailabilitySetsClient (read ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078793       1 azure_vmasclient.go:72] Azure AvailabilitySetsClient  (write ops) using rate limit config: QPS=10, bucket=100
I0901 15:25:01.078827       1 skus.go:120] PopulateNodeAndSkuInfo: Starting to populate node and disk sku information.
I0901 15:25:01.093092       1 skus.go:139] PopulateNodeAndSkuInfo: Populated node and disk sku information. NodeInfo=&{Standard_ND12s 0 eastus 0 0 0 0 0 0}
F0901 15:25:01.093111       1 azuredisk.go:195] Failed to get node info. Error: PopulateNodeAndSkuInfo: Could populate sku information. Error: populateSkuMap: Could not find SKU standard_nd12s in the sku map
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00000e001, 0xc000192200, 0xd0, 0x1ed)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/klog/v2/klog.go:1021 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x2ad9ce0, 0xc000000003, 0x0, 0x0, 0xc0000f0e70, 0x22e3e44, 0xc, 0xc3, 0x0)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/klog/v2/klog.go:970 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x2ad9ce0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1cb83a2, 0x22, 0xc00002e1d0, 0x1, ...)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/klog/v2/klog.go:751 +0x191
k8s.io/klog/v2.Fatalf(...)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/klog/v2/klog.go:1509
sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.(*Driver).Run(0xc00011e000, 0x7fff4737b9fd, 0x14, 0x0, 0x0, 0x1)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk/azuredisk.go:195 +0x786
main.handle()
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:75 +0x9c
main.main()
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:65 +0xae

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x2ad9ce0)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/klog/v2/klog.go:1164 +0x8b
created by k8s.io/klog/v2.init.0
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/klog/v2/klog.go:418 +0xdf

goroutine 51 [IO wait]:
internal/poll.runtime_pollWait(0x7f4dfce8deb8, 0x72, 0x0)
	/usr/lib/go-1.16/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0003d4818, 0x72, 0x0, 0x0, 0x1c8cb3a)
	/usr/lib/go-1.16/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go-1.16/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0003d4800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.16/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc0003d4800, 0x30, 0x30, 0x7f4e23b5a108)
	/usr/lib/go-1.16/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc00048e150, 0xc00022ed78, 0x40e078, 0x30)
	/usr/lib/go-1.16/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00048e150, 0x1b4e040, 0xc0003e97d0, 0x19f21e0, 0x2ab5220)
	/usr/lib/go-1.16/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc00015a700, 0x1ee4e00, 0xc00048e150, 0x0, 0x0)
	/usr/lib/go-1.16/src/net/http/server.go:2981 +0x285
net/http.Serve(...)
	/usr/lib/go-1.16/src/net/http/server.go:2529
main.serveMetrics(0x1ee4e00, 0xc00048e150, 0x461ee0, 0xc0004aa000)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:101 +0xca
main.serve.func1(0x1ee4e00, 0xc00048e150, 0x1d62860, 0xc0003c6350, 0xa)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:92 +0x7a
created by main.serve
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azurediskplugin/main.go:90 +0x189

goroutine 113 [select]:
k8s.io/apimachinery/pkg/util/wait.contextForChannel.func1(0xc0004e6000, 0xc00002e000, 0x1ee8550, 0xc00062c000)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:279 +0x87
created by k8s.io/apimachinery/pkg/util/wait.contextForChannel
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:278 +0x8c

goroutine 101 [select]:
net/http.(*persistConn).writeLoop(0xc0000c17a0)
	/usr/lib/go-1.16/src/net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	/usr/lib/go-1.16/src/net/http/transport.go:1744 +0xc9c

goroutine 47 [select]:
k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc000046090, 0xc000033fb8, 0xc0004e63c0, 0x0, 0x0)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:539 +0xf1
k8s.io/apimachinery/pkg/util/wait.PollUntil(0x6fc23ac00, 0xc000168fb8, 0xc0004e6000, 0x0, 0x0)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:492 +0xc5
k8s.io/apimachinery/pkg/util/wait.PollInfinite(0x6fc23ac00, 0xc000168fb8, 0x0, 0x0)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:464 +0x87
k8s.io/apimachinery/pkg/util/wait.PollImmediateInfinite(0x6fc23ac00, 0xc000168fb8, 0x1ee8550, 0xc00062c740)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:481 +0x74
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*delayedRouteUpdater).run(0xc00037bef0)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go:94 +0x52
created by sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).InitializeCloudFromConfig
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go:549 +0x6d6

goroutine 45 [IO wait]:
internal/poll.runtime_pollWait(0x7f4dfce8ddd0, 0x72, 0xffffffffffffffff)
	/usr/lib/go-1.16/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0003d4998, 0x72, 0xb00, 0xb41, 0xffffffffffffffff)
	/usr/lib/go-1.16/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go-1.16/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0003d4980, 0xc0001b6000, 0xb41, 0xb41, 0x0, 0x0, 0x0)
	/usr/lib/go-1.16/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0003d4980, 0xc0001b6000, 0xb41, 0xb41, 0xa5a, 0xc0001b60e2, 0x5)
	/usr/lib/go-1.16/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00011a128, 0xc0001b6000, 0xb41, 0xb41, 0x0, 0x0, 0x0)
	/usr/lib/go-1.16/src/net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc000116810, 0xc0001b6000, 0xb41, 0xb41, 0xa5a, 0xc000070c00, 0x0)
	/usr/lib/go-1.16/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc0000aa5f8, 0x1eb1e40, 0xc000116810, 0x40b6a5, 0x1a47a80, 0x1c0d820)
	/usr/lib/go-1.16/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc0000aa380, 0x1eb41a0, 0xc00011a128, 0x5, 0xc00011a128, 0xdf)
	/usr/lib/go-1.16/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0000aa380, 0x0, 0x0, 0x1)
	/usr/lib/go-1.16/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/lib/go-1.16/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc0000aa380, 0xc00017c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.16/src/crypto/tls/conn.go:1276 +0x165
bufio.(*Reader).Read(0xc00060d1a0, 0xc00015a2d8, 0x9, 0x9, 0xa60cab, 0xc000729c78, 0x406fa5)
	/usr/lib/go-1.16/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x1eb1ca0, 0xc00060d1a0, 0xc00015a2d8, 0x9, 0x9, 0x9, 0xc0000ff8b0, 0x1971dd7cf17a00, 0xc0000ff8b0)
	/usr/lib/go-1.16/src/io/io.go:328 +0x87
io.ReadFull(...)
	/usr/lib/go-1.16/src/io/io.go:347
golang.org/x/net/http2.readFrameHeader(0xc00015a2d8, 0x9, 0x9, 0x1eb1ca0, 0xc00060d1a0, 0x0, 0x0, 0x0, 0x0)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/golang.org/x/net/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00015a2a0, 0xc0003e9a10, 0x0, 0x0, 0x0)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000729fa8, 0x0, 0x0)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/golang.org/x/net/http2/transport.go:1819 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000103b00)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/golang.org/x/net/http2/transport.go:1741 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/golang.org/x/net/http2/transport.go:705 +0x6c5

goroutine 114 [select]:
k8s.io/apimachinery/pkg/util/wait.poller.func1.1(0xc0004e6480, 0x6fc23ac00, 0x0, 0xc0004e6420)
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:588 +0x135
created by k8s.io/apimachinery/pkg/util/wait.poller.func1
	/agent/_work/1/s/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:571 +0x8c

goroutine 100 [IO wait]:
internal/poll.runtime_pollWait(0x7f4dfce8dce8, 0x72, 0xffffffffffffffff)
	/usr/lib/go-1.16/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0004a1998, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/lib/go-1.16/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go-1.16/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0004a1980, 0xc000038000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.16/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0004a1980, 0xc000038000, 0x1000, 0x1000, 0x439c5c, 0xc00022ac38, 0x465260)
	/usr/lib/go-1.16/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000498048, 0xc000038000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.16/src/net/net.go:183 +0x91
net/http.(*persistConn).Read(0xc0000c17a0, 0xc000038000, 0x1000, 0x1000, 0xc0001602a0, 0xc00022ad40, 0x405755)
	/usr/lib/go-1.16/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc00050e180)
	/usr/lib/go-1.16/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc00050e180, 0x1, 0x0, 0x1, 0x4, 0x1, 0x3)
	/usr/lib/go-1.16/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc0000c17a0)
	/usr/lib/go-1.16/src/net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
	/usr/lib/go-1.16/src/net/http/transport.go:1743 +0xc77
```
</details>

**What you expected to happen**:
No crashloops.

**How to reproduce it (as minimally and precisely as possible)**:
Create AKS cluster v1.21.1 (`East US` in my case) with `standard_nd12s` and observe crashloops.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"b14bb200ea732d6667462a29d296d3daa511c911", GitTreeState:"clean", BuildDate:"2021-07-13T17:19:09Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?): between 6-10, 5 node pools
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): not relevant.

**Comment by andyzhangx** [comment]
the fix has been rolled out to all public regions now, pls check again, thanks.
