### ISSUE TITLE
[BUG] container insights pods restarting daily

### ISSUE THREAD

**Issue by georglabbe** [Azure/AKS#3609]
Hey there,

For a few days now, the `ama-logs` pods in three different k8s clusters have been restarting roughly once per day.
Each pod shows the same log output before restarting:

```
2023-04-14T06:13:09.0106170Z: Onboarding success. Sucessfully registered certificate with OMS Homing service.
Onboarding success
panic: interface conversion: interface {} is nil, not map[interface {}]interface {}

goroutine 17 [running, locked to thread]:
main.translateTelegrafMetrics(0x7f231b5bdda2?)
	/src/source/plugins/go/src/oms.go:834 +0x9ae
main.PostTelegrafMetricsToLA({0xc000122210?, 0x1, 0x7f231b56f3f8?})
	/src/source/plugins/go/src/oms.go:890 +0x150
main.FLBPluginFlush(0xc00004c180?, 0x0?, 0xc000002601?)
	/src/source/plugins/go/src/out_oms.go:76 +0x13e
2023-04-14T09:43:13Z E! [agent] Error writing to outputs.socket_writer: closing connection: write tcp 127.0.0.1:35752->127.0.0.1:25226: write: broken pipe
2023-04-14T09:43:28Z E! [agent] Error writing to outputs.socket_writer: dial tcp 0.0.0.0:25226: connect: connection refused
2023-04-14T09:43:43Z E! [agent] Error writing to outputs.socket_writer: dial tcp 0.0.0.0:25226: connect: connection refused
2023-04-14T09:43:58Z E! [agent] Error writing to outputs.socket_writer: dial tcp 0.0.0.0:25226: connect: connection refused
2023-04-14T09:44:13Z E! [agent] Error writing to outputs.socket_writer: dial tcp 0.0.0.0:25226: connect: connection refused
2023-04-14T09:44:28Z E! [agent] Error writing to outputs.socket_writer: dial tcp 0.0.0.0:25226: connect: connection refused
2023-04-14T09:44:43Z E! [agent] Error writing to outputs.socket_writer: dial tcp 0.0.0.0:25226: connect: connection refused
2023-04-14T09:44:58Z E! [agent] Error writing to outputs.socket_writer: dial tcp 0.0.0.0:25226: connect: connection refused
2023-04-14T09:45:13Z E! [agent] Error writing to outputs.socket_writer: dial tcp 0.0.0.0:25226: connect: connection refused
2023-04-14T09:45:28Z E! [agent] Error writing to outputs.socket_writer: dial tcp 0.0.0.0:25226: connect: connection refused
2023-04-14T09:45:43Z E! [agent] Error writing to outputs.socket_writer: dial tcp 0.0.0.0:25226: connect: connection refused
2023-04-14T09:45:58Z E! [agent] Error writing to outputs.socket_writer: dial tcp 0.0.0.0:25226: connect: connection refused
/opt/main.sh: line 1:   158 Aborted                 (core dumped) /opt/fluent-bit/bin/fluent-bit -c /etc/opt/microsoft/docker-cimprov/fluent-bit.conf -e /opt/fluent-bit/bin/out_oms.so
```

Describing any of the pods indicates, that the reason was a failed liveness probe due to the fluentbit process not running.

```
...
Last State:    Terminated
      Reason:      Error
      Message:     Fluentbit is not running

      Exit Code:    143
...
```

**Expected behavior**
Pods do not restart daily.

**Environment (please complete the following information):**
 - Kubernetes version: 1.24.9
 - Container insights image: mcr.microsoft.com/azuremonitor/containerinsights/ciprod:3.1.4
 
Any help would be greatly appreciated!

Thanks and best Regards,
Georg

**Comment by vdiec** [comment]
Hi @georglabbe ,  this fix has been rolled out. https://github.com/microsoft/Docker-Provider/blob/ci_prod/ReleaseNotes.md#04072023--
