### ISSUE TITLE
New Cluster: Heapster stuck in CrashLoopBackOff

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/AKS#387]
I created a brand new cluster in EastUS using B2 agent pool.

Here is heapster in CrashLoopBackOff
```
➜  ~ kubectl get pods
NAME                                                              READY     STATUS             RESTARTS   AGE
addon-http-application-routing-default-http-backend-66c97f644rk   1/1       Running            0          27m
addon-http-application-routing-external-dns-f9c5c6d5-pn22p        1/1       Running            0          27m
addon-http-application-routing-nginx-ingress-controller-64n4k6b   1/1       Running            2          27m
azureproxy-79c5db744-2vklk                                        1/1       Running            2          27m
heapster-7cd8dd888b-dqs9h                                         1/2       CrashLoopBackOff   9          27m
kube-dns-v20-7c556f89c5-6fbhl                                     3/3       Running            0          27m
kube-dns-v20-7c556f89c5-h6lwm                                     3/3       Running            0          27m
kube-proxy-9v4gj                                                  1/1       Running            0          27m
kube-svc-redirect-f29d4                                           1/1       Running            0          27m
kubernetes-dashboard-546f987686-tbc5x                             1/1       Running            4          27m
omsagent-hwk84                                                    1/1       Running            0          27m
tunnelfront-55c84579bf-ld6g4                                      1/1       Running            0          27m
```

Description
```
➜  ~ kubectl describe pod heapster-7cd8dd888b-dqs9h
Name:           heapster-7cd8dd888b-dqs9h
Namespace:      kube-system
Node:           aks-agentpool-38881274-0/10.240.0.4
Start Time:     Thu, 24 May 2018 09:48:14 -0500
Labels:         k8s-app=heapster
                pod-template-hash=3784884446
Annotations:    scheduler.alpha.kubernetes.io/critical-pod=
Status:         Running
IP:             10.244.0.4
Controlled By:  ReplicaSet/heapster-7cd8dd888b
Containers:
  heapster:
    Container ID:  docker://c409eac12e33ac04ccedf5d8d47777736313e0d78515244dcc8b9e07c6b07601
    Image:         k8s-gcrio.azureedge.net/heapster-amd64:v1.5.1
    Image ID:      docker-pullable://k8s-gcrio.azureedge.net/heapster-amd64@sha256:d4d10455d921802bdb004e7edfe423a2b2f88911319b48abf47e0af909f27f15
    Port:          <none>
    Host Port:     <none>
    Command:
      /heapster
      --source=kubernetes.summary_api:""
    State:          Running
      Started:      Thu, 24 May 2018 09:48:50 -0500
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     80m
      memory:  140Mi
    Requests:
      cpu:        80m
      memory:     140Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from heapster-token-k994b (ro)
  heapster-nanny:
    Container ID:  docker://2060b8cc6b09413573fcbcb8c937ca5ce5dba42ab376d5369c0a227ead5b4f6f
    Image:         k8s-gcrio.azureedge.net/addon-resizer:1.8.1
    Image ID:      docker-pullable://k8s-gcrio.azureedge.net/addon-resizer@sha256:507aa9845ecce1fdde4d61f530c802f4dc2974c700ce0db7730866e442db958d
    Port:          <none>
    Host Port:     <none>
    Command:
      /pod_nanny
      --cpu=80m
      --extra-cpu=0.5m
      --memory=140Mi
      --extra-memory=4Mi
      --threshold=5
      --deployment=heapster
      --container=heapster
      --poll-period=300000
      --estimator=exponential
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 24 May 2018 10:12:17 -0500
      Finished:     Thu, 24 May 2018 10:12:19 -0500
    Ready:          False
    Restart Count:  9
    Limits:
      cpu:     50m
      memory:  90Mi
    Requests:
      cpu:     50m
      memory:  90Mi
    Environment:
      MY_POD_NAME:       heapster-7cd8dd888b-dqs9h (v1:metadata.name)
      MY_POD_NAMESPACE:  kube-system (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from heapster-token-k994b (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  heapster-token-k994b:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  heapster-token-k994b
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                From                               Message
  ----     ------                 ----               ----                               -------
  Warning  FailedScheduling       27m (x6 over 28m)  default-scheduler                  0/1 nodes are available: 1 NodeNotReady.
  Normal   Scheduled              27m                default-scheduler                  Successfully assigned heapster-7cd8dd888b-dqs9h to aks-agentpool-38881274-0
  Normal   SuccessfulMountVolume  27m                kubelet, aks-agentpool-38881274-0  MountVolume.SetUp succeeded for volume "heapster-token-k994b"
  Normal   Pulling                27m                kubelet, aks-agentpool-38881274-0  pulling image "k8s-gcrio.azureedge.net/heapster-amd64:v1.5.1"
  Normal   Pulled                 26m                kubelet, aks-agentpool-38881274-0  Successfully pulled image "k8s-gcrio.azureedge.net/heapster-amd64:v1.5.1"
  Normal   Created                26m                kubelet, aks-agentpool-38881274-0  Created container
  Normal   Pulling                26m                kubelet, aks-agentpool-38881274-0  pulling image "k8s-gcrio.azureedge.net/addon-resizer:1.8.1"
  Normal   Started                26m                kubelet, aks-agentpool-38881274-0  Started container
  Normal   Pulled                 24m                kubelet, aks-agentpool-38881274-0  Successfully pulled image "k8s-gcrio.azureedge.net/addon-resizer:1.8.1"
  Normal   Created                23m (x4 over 24m)  kubelet, aks-agentpool-38881274-0  Created container
  Normal   Started                23m (x4 over 24m)  kubelet, aks-agentpool-38881274-0  Started container
  Normal   Pulled                 23m (x4 over 24m)  kubelet, aks-agentpool-38881274-0  Container image "k8s-gcrio.azureedge.net/addon-resizer:1.8.1" already present on machine
  Warning  BackOff                2m (x97 over 24m)  kubelet, aks-agentpool-38881274-0  Back-off restarting failed container
```

*Heapster Logs*

```
➜  ~ kubectl logs heapster-7cd8dd888b-dqs9h heapster | head -20
I0524 14:48:51.724146       1 heapster.go:78] /heapster --source=kubernetes.summary_api:""
I0524 14:48:51.724183       1 heapster.go:79] Heapster version v1.5.1
I0524 14:48:51.724529       1 configs.go:61] Using Kubernetes client with master "https://10.0.0.1:443" and version v1
I0524 14:48:51.724603       1 configs.go:62] Using kubelet port 10255
I0524 14:48:51.725844       1 heapster.go:202] Starting with Metric Sink
I0524 14:48:52.017454       1 heapster.go:112] Starting heapster on port 8082
E0524 14:49:21.817709       1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:30: Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
E0524 14:49:21.818953       1 reflector.go:190] k8s.io/heapster/metrics/heapster.go:328: Failed to list *v1.Pod: Get https://10.0.0.1:443/api/v1/pods?resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
E0524 14:49:21.819104       1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:30: Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
E0524 14:49:21.820089       1 reflector.go:190] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: Failed to list *v1.Namespace: Get https://10.0.0.1:443/api/v1/namespaces?resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
E0524 14:49:21.821152       1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:30: Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
E0524 14:49:22.818368       1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:30: Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
E0524 14:49:22.919059       1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:30: Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
E0524 14:49:22.919367       1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:30: Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
E0524 14:49:22.919418       1 reflector.go:190] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: Failed to list *v1.Namespace: Get https://10.0.0.1:443/api/v1/namespaces?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
E0524 14:49:22.919465       1 reflector.go:190] k8s.io/heapster/metrics/heapster.go:328: Failed to list *v1.Pod: Get https://10.0.0.1:443/api/v1/pods?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
E0524 14:49:23.818928       1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:30: Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
E0524 14:49:23.919656       1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:30: Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
E0524 14:49:23.920552       1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:30: Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
E0524 14:49:24.017361       1 reflector.go:190] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: Failed to list *v1.Namespace: Get https://10.0.0.1:443/api/v1/namespaces?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
➜  ~ kubectl logs heapster-7cd8dd888b-dqs9h heapster | tail -20
W0524 15:04:47.517089       1 reflector.go:323] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: watch of *v1.Namespace ended with: very short watch
W0524 15:04:47.522124       1 reflector.go:323] k8s.io/heapster/metrics/heapster.go:328: watch of *v1.Pod ended with: very short watch
W0524 15:05:48.630472       1 reflector.go:323] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: watch of *v1.Namespace ended with: very short watch
W0524 15:05:48.717416       1 reflector.go:323] k8s.io/heapster/metrics/heapster.go:328: watch of *v1.Pod ended with: very short watch
W0524 15:06:49.751413       1 reflector.go:323] k8s.io/heapster/metrics/heapster.go:328: watch of *v1.Pod ended with: very short watch
W0524 15:06:49.765769       1 reflector.go:323] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: watch of *v1.Namespace ended with: very short watch
W0524 15:07:50.899740       1 reflector.go:323] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: watch of *v1.Namespace ended with: very short watch
W0524 15:08:51.948755       1 reflector.go:323] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: watch of *v1.Namespace ended with: very short watch
W0524 15:09:24.878201       1 reflector.go:323] k8s.io/heapster/metrics/heapster.go:328: watch of *v1.Pod ended with: very short watch
W0524 15:09:53.026347       1 reflector.go:323] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: watch of *v1.Namespace ended with: very short watch
W0524 15:10:25.943945       1 reflector.go:323] k8s.io/heapster/metrics/heapster.go:328: watch of *v1.Pod ended with: very short watch
W0524 15:10:54.137800       1 reflector.go:323] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: watch of *v1.Namespace ended with: very short watch
W0524 15:11:27.040989       1 reflector.go:323] k8s.io/heapster/metrics/heapster.go:328: watch of *v1.Pod ended with: very short watch
W0524 15:11:55.243451       1 reflector.go:323] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: watch of *v1.Namespace ended with: very short watch
W0524 15:12:56.437041       1 reflector.go:323] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: watch of *v1.Namespace ended with: very short watch
W0524 15:13:57.635665       1 reflector.go:323] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: watch of *v1.Namespace ended with: very short watch
W0524 15:14:34.917610       1 reflector.go:323] k8s.io/heapster/metrics/heapster.go:328: watch of *v1.Pod ended with: very short watch
W0524 15:14:58.759901       1 reflector.go:323] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: watch of *v1.Namespace ended with: very short watch
W0524 15:15:36.042469       1 reflector.go:323] k8s.io/heapster/metrics/heapster.go:328: watch of *v1.Pod ended with: very short watch
W0524 15:15:59.853125       1 reflector.go:323] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: watch of *v1.Namespace ended with: very short watch
```

*Heapster Nanny Logs*

```
➜  ~ kubectl logs heapster-7cd8dd888b-dqs9h heapster-nanny
ERROR: logging before flag.Parse: I0524 15:12:19.220717       1 pod_nanny.go:64] Invoked by [/pod_nanny --cpu=80m --extra-cpu=0.5m --memory=140Mi --extra-memory=4Mi --threshold=5 --deployment=heapster --container=heapster --poll-period=300000 --estimator=exponential]
ERROR: logging before flag.Parse: I0524 15:12:19.220797       1 pod_nanny.go:76] Watching namespace: kube-system, pod: heapster-7cd8dd888b-dqs9h, container: heapster.
ERROR: logging before flag.Parse: I0524 15:12:19.220804       1 pod_nanny.go:77] storage: MISSING, extra_storage: 0Gi
ERROR: logging before flag.Parse: I0524 15:12:19.318199       1 pod_nanny.go:162] Failed to read data from config file "MISSING/NannyConfiguration": open MISSING/NannyConfiguration: no such file or directory, using default parameters
ERROR: logging before flag.Parse: I0524 15:12:19.318347       1 pod_nanny.go:166]
ERROR: logging before flag.Parse: I0524 15:12:19.318443       1 pod_nanny.go:101] cpu: , extra_cpu: , memory: , extra_memory:
panic: cannot parse '': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'

goroutine 1 [running]:
k8s.io/autoscaler/addon-resizer/vendor/k8s.io/apimachinery/pkg/api/resource.MustParse(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/kawych/go-tools/src/k8s.io/autoscaler/addon-resizer/vendor/k8s.io/apimachinery/pkg/api/resource/quantity.go:136 +0x253
main.main()
	/usr/local/google/home/kawych/go-tools/src/k8s.io/autoscaler/addon-resizer/nanny/main/pod_nanny.go:108 +0x6d5
```

**Comment by formerghostlyform** [comment]
I have the exact same problem.  I'd been troubleshooting all this morning to make sure it wasn't some problem with networks/subnets I chose, but re-creating the cluster ended with the same issue.

**Comment by feiskyer** [comment]
I believe aks team is fixing the issue. but meantime, the workaround is redeploying heapster, e.g. use heapster manifests here: https://gist.github.com/feiskyer/6a3cb7e67a11f35d024372366185c14e#file-heapster-yaml

**Comment by bramvdklinkenberg** [comment]
redeploying heapster worked for me as workaround.

`kubectl apply -f https://gist.githubusercontent.com/feiskyer/6a3cb7e67a11f35d024372366185c14e/raw/ad6c4b6a77af2150b508365cdb38758ddfa73d34/heapster.yaml`

**Comment by Mumrau** [comment]
For me,  `azure-proxy`, `tunnelfront`, and `k8s-dashboard` are also in `CrashLoopBackOff`, `kube-svc` sometimes is in `Error` state as well.
I'm having trouble provisioning clusters since yesterday afternoon (I'm in WestEurope), with few components failing in `kube-system`.
By the way, might someone be able to explain what does the `tunnelfront` component is useful for? I've managed to fix the others (at least for now), but this one is quite unclear to me.

**Comment by lastcoolnameleft** [comment]
Thanks @feiskyer for the update.  I have deleted those clusters, but will try your solution out next time I encounter it.

**Comment by lastcoolnameleft** [comment]
This seems to do the trick!  Thanks for the update.

@feiskyer Would you prefer I left this ticket open for others to discover (since the issue is still present), or close it since my issue is resolved?

**Comment by feiskyer** [comment]
@maxirus Could you provide the detailed error message in logs?

**Comment by emrekenci** [comment]
Here are some logs from when we saw this error. Applying heapster.yaml did resolve the issue in our case.

$ kubectl get pods -n kube-system

"Message": "Error creating: pods \"heapster-7cd8dd888b-\" is forbidden: error looking up service account kube-system/heapster: serviceaccount \"heapster\" not found",
 
"ContainerStatuses": [
                    {
                        "Name": "heapster",
                        "State": {
                            "Waiting": null,
                            "Running": {
                                "StartedAt": "2018-05-28T13:32:07Z"
                            },
                            "Terminated": null
                        },
                        "LastTerminationState": {
                            "Waiting": null,
                            "Running": null,
                            "Terminated": null
                        },
                        "Ready": true,
                        "RestartCount": 0,
                        "Image": "k8s-gcrio.azureedge.net/heapster-amd64:v1.5.1",
                        "ImageID": "docker-pullable://k8s-gcrio.azureedge.net/heapster-amd64@sha256:d4d10455d921802bdb004e7edfe423a2b2f88911319b48abf47e0af909f27f15",
                        "ContainerID": "docker://02645ece52b7b51935a4167477292877d7331406fc6a3961c59407b0d9fcf935"
                    },
                    {
                        "Name": "heapster-nanny",
                        "State": {
                            "Waiting": {
                                "Reason": "CrashLoopBackOff",
                                "Message": "Back-off 5m0s restarting failed container=heapster-nanny pod=heapster-7cd8dd888b-h4lwq_kube-system(56bec7c3-627b-11e8-8acd-0a58ac1f09aa)"
                            },
                            "Running": null,
                            "Terminated": null
                        },
                        "LastTerminationState": {
                            "Waiting": null,
                            "Running": null,
                            "Terminated": {
                                "ExitCode": 2,
                                "Signal": 0,
                                "Reason": "Error",
                                "Message": "",
                                "StartedAt": "2018-05-28T14:04:07Z",
                                "FinishedAt": "2018-05-28T14:04:09Z",
                                "ContainerID": "docker://cd89c57429308a70606719c1d90e577294bd87251ae4e947dfd86ae78753862e"
                            }
                        },

**Comment by Mumrau** [comment]
I tried but it looks like it just fixes the CrashLoop over the Heapster pod @emrekenci , but we do still have a problem that looks undetectable and most certainly provides from Azure troubles with AKS popularity these days, I have networking issues. 
I cannot access LoadBalanced service from the outside (even tho I do have an actual IP delivered by Azure), and even from the inside, a pod cannot `curl my-service` like it used to do.

I have several tickets with support, I'll see how it goes but it simply looks like they're having issues with staggering.

**Comment by epierotto** [comment]
I can see that the container `heapster-nanny` is the one that is crashing:



```bash
kubectl logs -p -c heapster-nanny heapster-7cd8dd888b-gz8g6
ERROR: logging before flag.Parse: I0531 09:28:22.027861       1 pod_nanny.go:64] Invoked by [/pod_nanny --cpu=80m --extra-cpu=0.5m --memory=140Mi --extra-memory=4Mi --threshold=5 --deployment=heapster --container=heapster --poll-period=300000 --estimator=exponential]
ERROR: logging before flag.Parse: I0531 09:28:22.028001       1 pod_nanny.go:76] Watching namespace: kube-system, pod: heapster-7cd8dd888b-gz8g6, container: heapster.
ERROR: logging before flag.Parse: I0531 09:28:22.028011       1 pod_nanny.go:77] storage: MISSING, extra_storage: 0Gi
ERROR: logging before flag.Parse: I0531 09:28:22.030798       1 pod_nanny.go:162] Failed to read data from config file "MISSING/NannyConfiguration": open MISSING/NannyConfiguration: no such file or directory, using default parameters
ERROR: logging before flag.Parse: I0531 09:28:22.030832       1 pod_nanny.go:166]
ERROR: logging before flag.Parse: I0531 09:28:22.030872       1 pod_nanny.go:101] cpu: , extra_cpu: , memory: , extra_memory:
panic: cannot parse '': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'

goroutine 1 [running]:
k8s.io/autoscaler/addon-resizer/vendor/k8s.io/apimachinery/pkg/api/resource.MustParse(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/kawych/go-tools/src/k8s.io/autoscaler/addon-resizer/vendor/k8s.io/apimachinery/pkg/api/resource/quantity.go:136 +0x253
main.main()
	/usr/local/google/home/kawych/go-tools/src/k8s.io/autoscaler/addon-resizer/nanny/main/pod_nanny.go:108 +0x6d5
```

This is the container config from the deployment that is currently crashing:
```bash
- command:
        - /pod_nanny
        - --cpu=80m
        - --extra-cpu=0.5m
        - --memory=140Mi
        - --extra-memory=4Mi
        - --threshold=5
        - --deployment=heapster
        - --container=heapster
        - --poll-period=300000
        - --estimator=exponential
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: k8s-gcrio.azureedge.net/addon-resizer:1.8.1
        imagePullPolicy: IfNotPresent
        name: heapster-nanny
        resources:
          limits:
            cpu: 50m
            memory: 90Mi
          requests:
            cpu: 50m
            memory: 90Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
```
I have another AKS 1.9.6 cluster and the version of the `heapster-nanny` image is: `image: k8s-gcrio.azureedge.net/addon-resizer:1.7` and is running properly.

This is the container config that is running properly:
```bash
- command:
        - /pod_nanny
        - --cpu=80m
        - --extra-cpu=0.5m
        - --memory=140Mi
        - --extra-memory=4Mi
        - --threshold=5
        - --deployment=heapster
        - --container=heapster
        - --poll-period=300000
        - --estimator=exponential
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: k8s-gcrio.azureedge.net/addon-resizer:1.7
        imagePullPolicy: IfNotPresent
        name: heapster-nanny
        resources:
          limits:
            cpu: 50m
            memory: 90Mi
          requests:
            cpu: 50m
            memory: 90Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
```

So far seems that the `k8s-gcrio.azureedge.net/addon-resizer:1.8.1` requires a different config and is crashing.

**Comment by necevil** [comment]
Are you guys still having this issue?
I saw the problem on a previous Cluster and then used the alternate image to fix it but the newest cluster deployed a few days ago due to the TLS Handshake bug (https://stackoverflow.com/questions/50726534/unable-to-connect-net-http-tls-handshake-timeout-why-cant-kubectl-connect) did not experience the behavior with Heapster.

Ie. Heapster was fine on the new Cluster.

**Comment by Mumrau** [comment]
It looks fixed on my side, provisioned a new cluster and it was okay on
kube-system components. Nonetheless, I didn't put stress or workload on it,
since I patched the previous cluster and have my solutions deployed on this
one.

**Comment by necevil** [comment]
@Mumrau Given my original (heapster crash cluster) I doubt that the crashloop was related to load as that Cluster had very low utilization — figured I would post back in case you were worried about causing the problem on a new cluster.  

If I run into it again after pushing the new one I spun up I will post back but my guess is this has been mitigated.

**Comment by bramvdklinkenberg** [comment]
with a newly deployed aks cluster I don't see the issue anymore.

**Comment by Mumrau** [comment]
I just wanted to point out that I did not perform deep testing over a fresh cluster, but it indeed looks fixed on their side.

Pretty sure this issue can be closed.

**Comment by lastcoolnameleft** [comment]
Thanks for the feedback!  Closing issue.

**Comment by niwsa** [comment]
Experiencing this in West Europe cluster.
