### ISSUE TITLE
Heapster (heapster-nanny) not starting with newly deployed AKS cluster 

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/AKS#390]
I deployed a new AKS cluster but heapster keeps crashen due to one of the 2 containers giving an error:

```
kubectl get pod --all-namespaces 
NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE
kube-system   heapster-7cd8dd888b-wpfnj               1/2       CrashLoopBackOff   10         29m
```

```
kubectl -n kube-system logs -f heapster-7cd8dd888b-wpfnj heapster-nanny 
ERROR: logging before flag.Parse: I0525 07:43:53.596436       1 pod_nanny.go:64] Invoked by [/pod_nanny --cpu=80m --extra-cpu=0.5m --memory=140Mi --extra-memory=4Mi --threshold=5 --deployment=heapster --container=heapster --poll-period=300000 --estimator=exponential]
ERROR: logging before flag.Parse: I0525 07:43:53.596627       1 pod_nanny.go:76] Watching namespace: kube-system, pod: heapster-7cd8dd888b-wpfnj, container: heapster.
ERROR: logging before flag.Parse: I0525 07:43:53.596683       1 pod_nanny.go:77] storage: MISSING, extra_storage: 0Gi
ERROR: logging before flag.Parse: I0525 07:43:53.598707       1 pod_nanny.go:162] Failed to read data from config file "MISSING/NannyConfiguration": open MISSING/NannyConfiguration: no such file or directory, using default parameters
ERROR: logging before flag.Parse: I0525 07:43:53.598783       1 pod_nanny.go:166] 
ERROR: logging before flag.Parse: I0525 07:43:53.598873       1 pod_nanny.go:101] cpu: , extra_cpu: , memory: , extra_memory: 
panic: cannot parse '': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'

goroutine 1 [running]:
k8s.io/autoscaler/addon-resizer/vendor/k8s.io/apimachinery/pkg/api/resource.MustParse(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/kawych/go-tools/src/k8s.io/autoscaler/addon-resizer/vendor/k8s.io/apimachinery/pkg/api/resource/quantity.go:136 +0x253
main.main()
	/usr/local/google/home/kawych/go-tools/src/k8s.io/autoscaler/addon-resizer/nanny/main/pod_nanny.go:108 +0x6d5
```

I tried deleteing the pod but that doesn't helped either. Also tried deleting and redeploying the cluster but same issue occures.

**Comment by bramvdklinkenberg** [comment]
See https://github.com/Azure/AKS/issues/387
