### ISSUE TITLE
[BUG]failed to auth with workload identity from time to time

### ISSUE THREAD

**Issue by juniwang** [Azure/AKS#4029]
**Describe the bug**
Hi team, we experienced several auth failures while using workload identity, which works well in majority of the time but we do see a few cases after enabled. Cannot find helpful information by search or on MS learn. Could you please help with the possible cause of the error? and what we can do to improve the situation? Thanks

Here is the detailed call stack:

Azure.Identity.AuthenticationFailedException: ClientAssertionCredential authentication failed: AADSTS501661: Request to External OIDC endpoint failed. Trace ID: 5625b5b1-6f4d-444f-8535-4d6dc5b00500 Correlation ID: c6f51d81-216a-4545-82ba-adc41b064ee3 Timestamp: 2023-12-09 02:40:08Z
 ---> MSAL.NetCore.4.57.0.0.MsalServiceException:
ErrorCode: invalid_request
Microsoft.Identity.Client.MsalServiceException: AADSTS501661: Request to External OIDC endpoint failed. Trace ID: 5625b5b1-6f4d-444f-8535-4d6dc5b00500 Correlation ID: c6f51d81-216a-4545-82ba-adc41b064ee3 Timestamp: 2023-12-09 02:40:08Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders, Func`2 onBeforePostRequestData)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders, Func`2 onBeforePostRequestHandler)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ILoggerAdapter logger)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ILoggerAdapter logger)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.GetAccessTokenAsync(CancellationToken cancellationToken, ILoggerAdapter logger)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
   at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientCoreAsync(String[] scopes, String tenantId, Boolean enableCae, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientAsync(String[] scopes, String tenantId, Boolean enableCae, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.ClientAssertionCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
StatusCode: 400
ResponseBody: {"error":"invalid_request","error_description":"AADSTS501661: Request to External OIDC endpoint failed. Trace ID: 5625b5b1-6f4d-444f-8535-4d6dc5b00500 Correlation ID: c6f51d81-216a-4545-82ba-adc41b064ee3 Timestamp: 2023-12-09 02:40:08Z","error_codes":[501661],"timestamp":"2023-12-09 02:40:08Z","trace_id":"5625b5b1-6f4d-444f-8535-4d6dc5b00500","correlation_id":"c6f51d81-216a-4545-82ba-adc41b064ee3"}
Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: c6f51d81-216a-4545-82ba-adc41b064ee3
Date: Sat, 09 Dec 2023 02:40:07 GMT

**To Reproduce**
1. Run command '...'
2. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22]
 - Kubernetes version [e.g. 1.24.3]: 1.27.7
 - CLI Extension version [e.g. 1.7.5] if applicable
 - Browser [e.g. chrome, safari] is applicable

**Additional context**

**Comment by vlardn** [comment]
Got the same issue today. The problem is because `AZURE_AUTHORITY_HOST, AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_FEDERATED_TOKEN_FILE` were not injected by webhook into app container environment. 
Actually, I found that workload identity webhook is no more installed by `az aks create ... --enable-workload-identity` command. The last time I saw this worked was Friday, i.e. 3 days ago.

The urgent workaround is to install it manually (and than delete pods or redeploy app to inject env variables):

```
export AZURE_TENANT_ID="$(az account show -s $SUBSCRIPTION --query tenantId -otsv)"
helm repo add azure-workload-identity https://azure.github.io/azure-workload-identity/charts
helm repo update
helm install workload-identity-webhook azure-workload-identity/workload-identity-webhook --namespace kube-system --set azureTenantID="${AZURE_TENANT_ID}"
```

**Comment by mymro** [comment]
We are experiencing a very similar issue in our application. From time to time the Workload identity just fails with a similar error and then works again. 

We are using the python library

**Comment by juniwang** [comment]
hi team, any updates?

**Comment by miwithro** [comment]
@juniwang @mymro thanks for opening the issue.  That error means AAD can't reach the OIDC endpoint to fetch the public keys.

Please see: https://azure.github.io/azure-workload-identity/docs/troubleshooting.html#aadsts90061-request-to-external-oidc-endpoint-failed

**Comment by juniwang** [comment]
@miwithro thanks for the link.  You are right it's because of transient AKS OIDC endpoint issue. It works most of the time which makes me believe there is no config issue in our side, aks or AAD. Actually there is another thread on Teams discussing the issue, it seems that there are transient failures resolving DNS. Support tickets were open to engage more people to trouble shoot.

**Comment by CocoWang-wql** [comment]
Close this one as issue is resolved. Thanks @juniwang @mymro for the feedback
