### ISSUE TITLE
Upgrade request required error

### ISSUE THREAD

**Issue by timwebster9** [Azure/AKS#451]
I'm experiencing a problem using AKS clusters.  I've tried Kubernetes v1.9.2 and v1.9.6 in UK South region.  I have the HTTP routing add-on enabled.

I've read this problem is something to do with Nginx and websockets and HTTP/2, but no idea how to troubleshoot it.  It also seems to have something to do with running `exec` commands against pods from inside the cluster.

Is there something about AKS that this kind of thing isn't supported?

Symptoms:

- You cannot exec into a pod from the Kubernetes dashboard.  You get this:

![image](https://user-images.githubusercontent.com/6548787/41651041-74b38630-7477-11e8-863a-2bebdb414c62.png)

- Using the Jenkins Kubernetes plugin, commands cannot be executed inside pods.  You get the following error.  This plugin works perfectly in other (non-AKS) clusters that I have.

```
java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:219)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:186)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
hudson.remoting.ProxyException: io.fabric8.kubernetes.client.KubernetesClientException: Upgrade request required
	at io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener.onFailure(ExecWebSocketListener.java:228)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:546)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:188)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zBurrito** [comment]
We have the same issue with using jenkins as our CI/CD pipeline. We use AKS 1.9.6 in West Europe with RBAC enabled.
The exec command is initiated by the jenkins-slave to jenkins, so the connection doesn't pass through nginx. I think this is an issue related to RBAC.

**Comment by RonaldV** [comment]
We also have the same problem using Jenkins and Kubernetes with RBAC. Also AKS version 1.9.6 in West Europe.

**Comment by SorenMaagaard** [comment]
I have the same issue as well using Jenkins (jenkins-x.io) on AKS. I have tried the following combinations:
1.9.6 in westeurope with RBAC using various roles including cluster-admin.
1.9.6 in westeurope without RBAC.
1.8.10 in westeurope without RBAC.
All with the same error as above. The exact same deployment works fine on e.g. GKE.

**Comment by Flask** [comment]
Most likely related to #434

**Comment by bartse** [comment]
Ive managed to fix the issue for the jenkins kuberentes plugin. Using the solution of  @Flask.
You need to change the default kubernetes URL in the cloud section of the jenkins configuration.
Change the default value to ****-****.hcp.westeurope.azmk8s.io.
(for anyone wonrdering you can find the URL easily in the kubectl config on your local machine(kubectl config view)

**Comment by rite2nikhil** [comment]
This issue should be fixed for new cluster creates in all regions. Please provide feedback if it is still not working.

**Comment by mboersma** [comment]
"upgrade request required" has been fixed in AKS. @timwebster9 please re-open if you don't see this behaving properly now.
