### ISSUE TITLE
Users can not disable the Kubernetes dashboard via the az aks disable-addons command

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#786]
As part of the follow up for the recent Kubernetes Dashboard CVE users have asked how to force-disable the Kubernetes dashboard deployed with every AKS cluster to temporarily mitigate the issue as well as other cases where users do not want or need the kubernetes dashboard to be automatically restored or managed by AKS.

This bug tracks a feature request to the Azure CLI to enable the following commands:

`az aks disable-addons -a kube-dashboard -n X -g Y`

and:

`az aks enable-addons -a kube-dashboard -n X -g Y`

**Comment by jnoller** [comment]
This has been shipped, is available and functionality confirmed. Please see the AKS releases page. https://github.com/Azure/AKS/releases

**Comment by tehleet** [comment]
Where do you see a possiblity to disable dashboard? Provided command fails.

**Comment by jnoller** [comment]
Reopening due to regression

**Comment by timwebster9** [comment]
is this the regression? (az cli version 2.0.64):

```
Tims-MacBook-Pro-4:~ timw$ az aks disable-addons -a kube-dashboard -n aks-sbox-cluster-00 -g sbox-00-rg
The command failed with an unexpected error. Here is the traceback:

'kube-dashboard'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.64/libexec/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.64/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.64/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.64/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 611, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.64/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.64/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 588, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.64/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 297, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.64/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 453, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.64/libexec/lib/python3.7/site-packages/azure/cli/command_modules/acs/custom.py", line 1636, in aks_disable_addons
    no_wait=no_wait
  File "/usr/local/Cellar/azure-cli/2.0.64/libexec/lib/python3.7/site-packages/azure/cli/command_modules/acs/custom.py", line 1846, in _update_addons
    addon = ADDONS[addon_arg]
KeyError: 'kube-dashboard'
```

**Comment by jnoller** [comment]
@timwebster9 Yes, that's why I re-opened the issue

**Comment by WebSpider** [comment]
Just confirming this seems to work again using az version 2.0.67

Command output:

```
$ az aks disable-addons -a kube-dashboard -n XXX-g NNN --verbose
The behavior of this command has been altered by the following extension: aks-preview
NAMESPACE     LAST SEEN   TYPE     REASON             OBJECT                 MESSAGE
kube-system   0s          Normal   ScalingReplicaSet   deployment/kubernetes-dashboard   Scaled down replica set kubernetes-dashboard-7b55c6f7b9 to 0
kube-system   1s          Normal   SuccessfulDelete    replicaset/kubernetes-dashboard-7b55c6f7b9   Deleted pod: kubernetes-dashboard-7b55c6f7b9-c6wlx
kube-system   0s          Normal   Killing             pod/kubernetes-dashboard-7b55c6f7b9-c6wlx    Killing container with id docker://main:Need to kill Pod
{
  "aadProfile": null,
  "addonProfiles": {
    "kubeDashboard": {
      "config": null,
      "enabled": false
    }
  },
  "agentPoolProfiles": [
    {
      "availabilityZones": null,
      "count": 1,
      "enableAutoScaling": true,
      "maxCount": 5,
      "maxPods": 110,
      "minCount": 1,
      "name": "nodepool1",
      "orchestratorVersion": "1.13.5",
      "osDiskSizeGb": 30,
      "osType": "Linux",
      "provisioningState": "Succeeded",
      "type": "VirtualMachineScaleSets",
      "vmSize": "Standard_B2s",
      "vnetSubnetId": null
    }
  ],
  "apiServerAuthorizedIpRanges": null,
  "dnsPrefix": "`XXX",
  "enablePodSecurityPolicy": null,
  "enableRbac": true,
  "fqdn": "XXX.hcp.eastus.azmk8s.io",
  "id": "/subscriptions/YYY/resourcegroups/NNN/providers/Microsoft.ContainerService/managedClusters/XXX",
  "identity": null,
  "kubernetesVersion": "1.13.5",
  "linuxProfile": {
    "adminUsername": "azureuser",
    "ssh": {
      "publicKeys": [
        {
          "keyData": "ssh-rsa snip"
        }
      ]
    }
  },
  "location": "eastus",
  "maxAgentPools": 1,
  "name": "XXX",
  "networkProfile": {
    "dnsServiceIp": "10.0.0.10",
    "dockerBridgeCidr": "172.17.0.1/16",
    "loadBalancerSku": "Basic",
    "networkPlugin": "kubenet",
    "networkPolicy": null,
    "podCidr": "10.244.0.0/16",
    "serviceCidr": "10.0.0.0/16"
  },
  "nodeResourceGroup": "MC_XXX_eastus",
  "provisioningState": "Succeeded",
  "resourceGroup": "NNN",
  "servicePrincipalProfile": {
    "clientId": "ZZZ",
    "secret": null
  },
  "tags": null,
  "type": "Microsoft.ContainerService/ManagedClusters",
  "windowsProfile": null
}
command ran in 76.315 seconds.
``

**Comment by rudolphjacksonm** [comment]
@WebSpider @jnoller can confirm this is working just fine now in `2.0.67` 👍

**Comment by jnoller** [comment]
Ugh, thanks - I missed closing it.
