### ISSUE TITLE
GA Support for Virtual Machine Scale Sets (VMSS)

### ISSUE THREAD

**Issue by jnoller** [Azure/AKS#945]
This issue tracks the state of VMSS support in AKS. Currently this is public preview and you can see opt-in instructions here: https://github.com/Azure/AKS/blob/master/previews.md#preview-features

**Comment by jnoller** [comment]
This is in public preview: https://github.com/Azure/AKS/blob/master/previews.md#virtual-machine-scale-sets-vmss--cluster-autoscaler

**Comment by rewt** [comment]
Running into issue deploying elasticsearch

`[2019-05-20T20:44:52,897][WARN ][i.n.c.AbstractChannelHandlerContext] [es-elasticsearch-data-0] An exception 'java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.lang.Thread.start0(Native Method) ~[?:?]
	at java.lang.Thread.start(Thread.java:804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1354) ~[?:?]
	at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.java:98) ~[elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1046) ~[elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:932) ~[elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:763) ~[elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53) ~[transport-netty4-client-6.7.0.jar:6.7.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [netty-common-4.1.32.Final.jar:4.1.32.Final]
	at java.lang.Thread.run(Thread.java:835) [?:?]
[25.719s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.`

This same code works fine on non-VMSS AKS cluster.

Is there a limit on # of processes?  Memory appears to be checking out just fine.  Running on `Standard_E8s_v3 (3 instances)`

**Comment by immunochomik** [comment]
Just wanted to say that autoscaling based on load is a necessary feature of a managed k8s cluster. So VMSS is extremely important to AKS users!

**Comment by tomkerkhove** [comment]
@immunochomik 	That is correct, do you have a concern on this? Because it's already available in public preview.

**Comment by jluk** [comment]
@jnoller can we scope this issue a bit? Is this one meant to be closed upon VMSS GA?

**Comment by jnoller** [comment]
@rewt if you have an issue, please file a new bug or otherwise raise a support issue. This is a feature card and not related to any other bug.

**Comment by amadav** [comment]
Is there a way using java sdk to create cluster with VMSS enabled? I have already enabled the preview feature to be created from CLI. Would appreciate any pointers.

**Comment by jluk** [comment]
@amadav this is defined by the agentpooltype, hope this helps.

https://github.com/Azure/azure-sdk-for-java/blob/master/containerservice/resource-manager/v2019_04_01/src/main/java/com/microsoft/azure/management/containerservice/v2019_04_01/AgentPoolType.java#L18

**Comment by amadav** [comment]
Thanks a lot @jluk. I will try this. I am trying to enable cluster autoscaler on this aks cluster and figuring how to do that outside CLI would be my next part of exploration :)

**Comment by jluk** [comment]
@amadav FYI we've generated a more recent API for the Java SDK below:

https://github.com/Azure/azure-sdk-for-java/tree/master/containerservice/resource-manager/v2019_06_01/src/main/java/com/microsoft/azure/management/containerservice/v2019_06_01

**Comment by amadav** [comment]
Thanks @jluk, but I am wondering how this is different than the azure-mgmt-containerservice jar that comes packaged as transient dependency with azure management libraries 1.24.1. Why do two projects exist for sdk and java-libs.

**Comment by jluk** [comment]
@amadav the referenced issue for active work on new support is below from @yaohaizh . He can speak to the difference between the two.

https://github.com/Azure/azure-libraries-for-java/issues/811

**Comment by jluk** [comment]
Closing as VMSS is now GA as noted in release.

https://github.com/Azure/AKS/releases/tag/2019-09-09
